---
title: "data cleaning/checking relationship"
author: "Zhi Yuh Ou Yang (301322064)"
date: "11/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("mice")
```

```{r}
require(ggplot2)
require(class)
require(rpart)
require(randomForest)
require(dplyr)
require(rpart.plot)
require(reshape)
require(tidyr)
require(GGally)
require(caret)
require(corrplot)
require(glmnet)
require(mice)
```

```{r}
df <- read.csv("NewData.csv")

yes <- subset(df, SUBSCRIBE == "Y")

no <- subset(df, SUBSCRIBE == "N")

na <- subset(df, is.na(df$SUBSCRIBE))

#select the column for trainset
DA <- select(df, -Record, -Disc, -Title, -LastOrder, -Weeks3Meals, Sample)
```

```{r}
#get rid of SUBSCRIBE first.
woutSUB <- select(DA, -SUBSCRIBE) 

naIncome <- subset(woutSUB, is.na(woutSUB$DA_Income))

#use mice to impute the missing value
tempdata <- mice(woutSUB, seed = 500)
#create five different dataset from MICE method
completeMice1 <- complete(tempdata, 1)
completeMice2 <- complete(tempdata, 2)
completeMice3 <- complete(tempdata, 3)
completeMice4 <- complete(tempdata, 4)
completeMice5 <- complete(tempdata, 5)

#get rid of NA without imputation
completeMice0 <- woutSUB[!is.na(woutSUB$DA_Income), ]

#merge the 6 different datasets
completeMice0 <- merge(completeMice0, DA[, c("custid", "SUBSCRIBE")], by="custid")
completeMice1 <- merge(completeMice1, DA[, c("custid", "SUBSCRIBE")], by="custid")
completeMice2 <- merge(completeMice2, DA[, c("custid", "SUBSCRIBE")], by="custid")
completeMice3 <- merge(completeMice3, DA[, c("custid", "SUBSCRIBE")], by="custid")
completeMice4 <- merge(completeMice4, DA[, c("custid", "SUBSCRIBE")], by="custid")
completeMice5 <- merge(completeMice5, DA[, c("custid", "SUBSCRIBE")], by="custid")
```

```{r}
#split
test1 <- completeMice1[rowSums(is.na(completeMice1)) > 0,]
train1 <- completeMice1[rowSums(is.na(completeMice1)) == 0,]
```

```{r}
ggpairs(train1, columns = c(2:6, 15), mapping = aes(color = SUBSCRIBE), lower=list(combo=wrap("facethist", binwidth=0.5)), progress = FALSE)
ggpairs(train1, columns = c(7:10, 15), mapping = aes(color = SUBSCRIBE), lower=list(combo=wrap("facethist", binwidth=0.5)), progress = FALSE)
ggpairs(train1, columns = c(11:14, 15), mapping = aes(color = SUBSCRIBE), lower=list(combo=wrap("facethist", binwidth=0.5)), progress = FALSE)
```

```{r}
train1Con <- select(train1, -SUBSCRIBE, -Sample)
#test for linear association - pearson
M1 <- cor(train1Con, method = "pearson")
corrplot(M1, method = "color")
a <- corrplot(M1, method = "number")
```

```{r}
#test for non-linear association - spearman
M2 <- cor(train1Con, method = "spearman")
corrplot(M2, method = "color")
```
