---
title: "logistic/multinomial"
author: "Zhi Yuh Ou Yang (301322064)"
date: "11/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#5-fold cross validation
k = 5
n = floor(nrow(train1)/k) #size of each fold
acc2 <- rep(NA, k) #store the accuracy here.

  
for (i in 1:k) {
  s1 <- ((i - 1) * n + 1) #the start of the subset.
  s2 <- (i * n) #the end of the subset.
  subset <- s1:s2 #the range of subset.
  
  cvTrain <- train1[-subset, ]
  cvTest <- train1[subset, ]
  cvTestX <- select(cvTest, -SUBSCRIBE)
  ActualL <- cvTest$SUBSCRIBE
  
  LogReg <- glm(SUBSCRIBE ~ ., family = binomial(link = 'logit'), data = cvTrain)
  LogPred <- predict(LogReg, cvTestX, type = "response")
  LogPred <- ifelse(LogPred > 0.5, "high", "low")
  acc2[i] <- sum(DTPred == cvTest[, "SUBSCRIBE"])/nrow(cvTest)
  print(paste("The accuracy for fold", i, "is", acc2[i], "."))
}
```

```{r}
#the mean accuracy for 5-fold decision tree method.
paste("The mean accuracy for 5-fold decision tree method is", round(mean(acc), 4), ".")

#the estimate of the loss for 5-fold decision tree method.
paste("The estimate of the loss for 5-fold random forest method is", round(1 - mean(acc), 4), ".")
```